apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  myvalue: "Hello World"
  testvalue: "Hello World"
  # drink: {{ .Values.favorite.drink }}
  # food: {{ .Values.favorite.food }}
  # drink: {{ quote .Values.favorite.drink }}
  # food: {{ quote .Values.favorite.food }}
  drink: {{ .Values.favorite.drink | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 80;
        location / {
          return 200 "===============================\n\n   This is your helm deploy!   \n\n===============================\n";
        }
      }
    }