apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alpine
  namespace: flux-system
spec:
  chart:
    spec:
      chart: https://example.com/charts/alpine-0.1.2.tgz
      sourceRef:
        kind: GitRepository
        name: alpine
  interval: 1m0s
  install:
    createNamespace: true
  targetNamespace: default